### ISSUE TITLE
[Question] Dominio o infraestructura

### ISSUE THREAD

**Issue by pana1990** [CodelyTV/php-ddd-example#112]
Tenéis la interfaz middleware en infraestructura https://github.com/CodelyTV/cqrs-ddd-php-example/blob/master/src/Shared/Infrastructure/Bus/Middleware/Middleware.php

Está clase no debería ir en dominio, enlazado a esto habría algún caso de uso que provocara tener una interfaz en infraestructura?¿

**Comment by pana1990** [comment]
Up

**Comment by pana1990** [comment]
up

**Comment by pana1990** [comment]
up

**Comment by pana1990** [comment]
up

**Comment by pana1990** [comment]
up

**Comment by rgomezcasas** [comment]
Ahora mismo ya no hay middlewares en el bus. Cuando los volvamos a meter estará la interfaz en Dominio, bien visto :)

Pd. up, up, up, up 😂

**Comment by pana1990** [comment]
@rgomezcasas Gracias por tu respuesta, todo claro ;)
