### ISSUE TITLE
Crear grupo de discord o slack

### ISSUE THREAD

**Issue by pana1990** [CodelyTV/php-ddd-example#115]
Estaría super bien crear un grupo de slack o discord en que los alumnos y algunos tutores podamos charlar de los distintos temas de la plataforma (ddd, tdd, php, symfony, docker...)

Sorry de antemano si este no es el mejor lugar para comentar esto.

Un abrazo chicos.

**Comment by pana1990** [comment]
Up

**Comment by pana1990** [comment]
up

**Comment by pana1990** [comment]
up

**Comment by pana1990** [comment]
Up

**Comment by juanBL** [comment]
Buenas @pana1990, me permito el lujo de contestarte.

Existe un Slack que se llama BcnEng y allí hay un canal #codelytv donde se hablan estos temas que comentas.

Te he enviado una invitación a tu email!!

**Comment by pana1990** [comment]
@juanBL  muchisimas gracias por la invitación, @JavierCane  @rgomezcasas  estaría bien dejar un enlace de referencia en el project, este recurso es oro puro.

**Comment by rgomezcasas** [comment]
Haremos un vídeo hablando de comunidades y allí lo pondremos!

Si acabamos creando algo propio para nosotros te lo haremos saber también!

Saludos!!
