### ISSUE TITLE
Question about validation

### ISSUE THREAD

**Issue by anaelChardan** [CodelyTV/php-ddd-example#122]
Hey, thanks a lot for the repo.

I've tried to play with the repository and I wanted to see where would you do validation?
I've created a video with a non existent course.
I wonder how would you do if you wanted to validate that the course exists ? 

Thanks in advance :)

**Comment by anaelChardan** [comment]
So sad :-(

**Comment by rgomezcasas** [comment]
Hey sorry I just saw this!

We could modify the `VideoCreator` to something like this:

```php
<?php

declare(strict_types = 1);

namespace CodelyTv\Mooc\Videos\Application\Create;

use CodelyTv\Mooc\Shared\Domain\Courses\CourseId;
use CodelyTv\Mooc\Shared\Domain\Videos\VideoUrl;
use CodelyTv\Mooc\Videos\Domain\Video;
use CodelyTv\Mooc\Videos\Domain\VideoId;
use CodelyTv\Mooc\Videos\Domain\VideoRepository;
use CodelyTv\Mooc\Videos\Domain\VideoTitle;
use CodelyTv\Mooc\Videos\Domain\VideoType;
use CodelyTv\Shared\Domain\Bus\Event\DomainEventPublisher;
use CodelyTv\Shared\Domain\Bus\Query\QueryBus;

final class VideoCreator
{
    private $repository;
    private $bus;
    private $publisher;

    public function __construct(VideoRepository $repository, QueryBus $bus, DomainEventPublisher $publisher)
    {
        $this->repository = $repository;
        $this->bus        = $bus;
        $this->publisher  = $publisher;
    }

    public function create(VideoId $id, VideoType $type, VideoTitle $title, VideoUrl $url, CourseId $courseId): void
    {
        $this->ensureVideoCourseExist($courseId);

        $video = Video::create($id, $type, $title, $url, $courseId);

        $this->repository->save($video);

        $this->publisher->publish(...$video->pullDomainEvents());
    }

    private function ensureVideoCourseExist(CourseId $id): void
    {
        // We should create this query first. This query will throw an exception if the course is not found
        $this->bus->ask(new FindCourseQuery($id->value()));
    }
}
```

**Comment by anaelChardan** [comment]
And if the command bus is asynchronous how you tell the user ? ;)

**Comment by rgomezcasas** [comment]
If it's async you could do 2 approaches:

1. When the client do the REST petition it should also include a `requestId`. Then the client could do pulling every X millis to a `/command/status/{requestId}` endpoint to see the status
2. Instead you can do this using a websocket or [mercure](https://mercure.rocks/)

**Comment by JavierCane** [comment]
I would like to add just a subtle detail that maybe it's worth it to mention:

The fact of having an async _command_ bus would make no difference between having to validate if the course exists or not.

I mean, we would be using the _query_ bus in order to ask information from other modules and bounded contexts so, we could be having an async command bus, but a sync query bus.

In that case (being the command bus the only async one), we could go for an approach such as the suggested ones by @rgomezcasas. But we would need to go for that approaches even if we don't ask anything to the query bus 😊

**Comment by anaelChardan** [comment]
Ok, thanks that was exactly what I was thinking about, you confirm my opinions ;)
Thanks a lot!
