### ISSUE TITLE
Error when goes to -> 2. Go to the API health check page

### ISSUE THREAD

**Issue by xpalacincreditoh** [CodelyTV/php-ddd-example#142]
When goes to url http://api.codelytv.localhost:8030/health-check to the API health check page, show a warning:

Warning: file_put_contents(/app/apps/mooc/backend/var/cache/test/CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainerDeprecations.log): failed to open stream: No such file or directory

The problem is with permissions when execute make build i need sud and create fies with root.
When solve this return: {"mooc-backend":"ok","rand":1}

**Comment by bareser** [comment]
Hello, I have the same error.
Can you give me more details?
Thanks!
