### ISSUE TITLE
health check error before make build

### ISSUE THREAD

**Issue by nabby27** [CodelyTV/php-ddd-example#152]
```
file_put_contents(/app/apps/mooc/backend/var/cache/test/CodelyTv_Apps_Mooc_Backend_MoocBackendKernelTestDebugContainerDeprecations.log): failed to open stream: No such file or directory
```

```
Unable to create the cache directory (/app/apps/mooc/backend/var/cache/test)
```

This errors show when I go to health check route after `make build`.

I don't know how to resolve. Any help?

**Comment by JavierCane** [comment]
Hi!

Thanks for the report 🙂

Did you solve it? Should we have to change anything?

Thanks!

**Comment by nabby27** [comment]
@JavierCane 

It happened because I forgot to change the name of a container in the configuration, sorry for the inconvenience.

Now i get this error [https://github.com/CodelyTV/php-ddd-example/issues/147](https://github.com/CodelyTV/php-ddd-example/issues/147). Waiting to see if there is any other solution

**Comment by bareser** [comment]
Hello, I have the same error.
Can you give me more details?
Thanks!
