### ISSUE TITLE
How can a dependency be added to the project?

### ISSUE THREAD

**Issue by nabby27** [CodelyTV/php-ddd-example#154]
I do not have composer installed on my local computer and I see that it is not installed in the php docker container, is there a way to install a dependency in the project that I am not seeing? or do I have to install composer on my local computer?

**Comment by JavierCane** [comment]
You can just edit the `composer.json` file and run a `make composer-update` command, or you can define a new task such as `composer-require` in the `Makefile` such as [the current `composer-update`](https://github.com/CodelyTV/php-ddd-example/blob/master/Makefile#L12) which would also require the arguments of the dependency to require and it version.

It would be awesome if you want to contribute with a PR implementing it 😊
