### ISSUE TITLE
Ejecutar en windows

### ISSUE THREAD

**Issue by bareser** [CodelyTV/php-ddd-example#157]
Hola chicos, soy un principiante y no tengo mucha idea, vuestra documentación para arrancar el proyecto creo que está basada en linux o mac, pero para lo que tenemos windows. ¿Algunas nociones básicas para poder echar a andar?
Estoy intentado buscar información pero no me aclaro.
Gracias de antemano.

**Comment by bareser** [comment]
Hola de nuevo, creo que he conseguido echar a andar los contenedores de docker, me he instalado en mi PC el docker-tools para windows y con el comando de docker-compose up ya levanto los servicios.
Pero no logro acceder a las URL, esta URL, por ejemplo, no me funciona http://api.codelytv.localhost:8030/health-check
no sé si es la correcta para ver algo o no.
En este ejemplo ¿Se incluye algun frontend de ejemplo? ¿cual sería la URL para acceder?
Gracias

**Comment by SoyUnEmilio** [comment]
Has puesto en c:\windows\system32\etc\drivers\hosts la entrada
correspondiente para que te resuelva el host a tu IP local 127.0.0.1?

**Comment by SoyUnEmilio** [comment]
Perdona, la ruta correcta es *c:\Windows*\*System32*\*Drivers*\*etc*\*hosts*

**Comment by bareser** [comment]
@SoyUnEmilio gracias por contestar, en el archivo host que me indicas tengo esto:
¿Debería añadir algo más?

192.168.1.39 host.docker.internal
192.168.1.39 gateway.docker.internal
# Added by Docker Desktop
192.168.1.37 host.docker.internal
192.168.1.37 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

**Comment by bareser** [comment]
@SoyUnEmilio  he agregado la siguiente linea al archivo host:
127.0.0.1 	api.codelytv.localhost
pero sigue sin funcionar ninguna URL, estoy probando la URL http://api.codelytv.localhost:8030/health-check
No logro saber que me falta para lograr probar este proyecto y ver algo.

Tengo los contenedores de docker funcionando:
![image](https://user-images.githubusercontent.com/24532285/82737924-7bda8480-9d34-11ea-9262-97c330661294.png)

**Comment by rgomezcasas** [comment]
Hey!

Si vas directamente a `http://localhost:8030` te deja?

**Comment by alberto-ln** [comment]
Te recomiendo que te registres en el programa de windows insider para poder obtener WSL 2 (que permite utilizar el docker instalado en en tu windows, la 1 no), en resumen te crea un susbistema de linux, así puedes seguir la mayoría de los tutoriales y guías que encuentres sin tener que andar dándote cabezazos, dado que todos los comandos te servirán igual.

**Comment by rgomezcasas** [comment]
Toda la razón lo que propone @alberto-ln! Fixeado con eso :)

Gracias!!
