### ISSUE TITLE
Add CodeStyle

### ISSUE THREAD

**Issue by rgomezcasas** [CodelyTV/php-ddd-example#16]

**Comment by JavierCane** [comment]
Desc: We should add the CodeSniffer rules and check in the `make test` command, and include also PHP CS Fixer inspections. Or should we replace CodeSniffer by CS Fixer? Does CS Fixer include all we need (PSR-2 and so on)?

**Comment by zerai** [comment]
Hi, any news about this open issue?
I don't know CodeSniffer, but I can provide a PR for CS Fixer.
WDYT?

**Comment by jeslopcru** [comment]
I'm wondering if you can close this issue because it was solved when [`codelytv/coding-style`](https://github.com/CodelyTV/php-ddd-example/blob/ecf8d27ea25885a8f21cbc60da87e9912daf4aba/composer.json#L64C1-L65C1) was added? and in the `Makefile` there is a command  called `lint` 🤔 
Good job!

**Comment by rgomezcasas** [comment]
Totally @jeslopcru!!! 🙌
