### ISSUE TITLE
Execute install on Windows 10

### ISSUE THREAD

**Issue by bareser** [CodelyTV/php-ddd-example#160]
Hello, I have windows 10 home, I have installed Docker Toolbox and I have run the make build command.
It has started to download packages but in the end it shows me this error:

$ make build
Unable to find image 'clevyr/prestissimo:latest' locally
latest: Pulling from clevyr/prestissimo
aad63a933944: Pull complete b61c449d5d91: Pull complete 3fde16e1397a: Pull complete b1096698ab2a: Pull complete e8dc88fe9f8a: Pull complete f35615996f60: Pull complete 97f4e139977b: Pull complete 649bec891de8: Pull complete af6bcad316b1: Pull complete e2ada3326131: Pull complete 81688d4a328f: Pull complete 447b1083cc14: Pull complete 3da2115fa6d3: Pull complete 41732dd0e67d: Pull complete b0cdc13664f2: Pull complete 99887356f7cb: Pull complete Digest: sha256:df1b9ae00bea8ca2485c5b8649842501b52ed9057a9c95c29ab68d4f9d40f3c8
Status: Downloaded newer image for clevyr/prestissimo:latest
**docker: Error response from daemon: invalid mode: /app.
See 'docker run --help'.
make: *** [Makefile:13: composer-install] Error 125**

What can I do?

**Comment by rgomezcasas** [comment]
Hey! I don't have a windows and can't reproduce it. But can you try to run:
```sh
@docker run --rm --interactive --volume PATH_WHERE_YOU_CLONED_THIS:/app --user $(id -u):$(id -g) \
	clevyr/prestissimo $(CMD) \
		--ignore-platform-reqs \
		--no-ansi \
		--no-interaction
```
Changing `PATH_WHERE_YOU_CLONED_THIS` with your path?

**Comment by bareser** [comment]
In the end, I signed up for the Windows Insider program and installed ubuntu, and everything works with linux. Linux is easier to work with.
Everything is designed to work with Linux systems.
