### ISSUE TITLE
allSubscribedTo Dice que retorna un callable y tendria que ser un array 

### ISSUE THREAD

**Issue by keldrox** [CodelyTV/php-ddd-example#179]
Creo que el método allSubscribedTo su tipo de retorno es incorrecto ya que marca un callable y tendría que ser un array, ya que el consumidor de Mysql después de la llamada lo uso en un bucle

https://github.com/CodelyTV/php-ddd-example/blob/907793aad82877be6ab3286df608eb4382b050e3/src/Shared/Infrastructure/Bus/Event/DomainEventSubscriberLocator.php#L23

**Comment by rgomezcasas** [comment]
Fixed by you :) https://github.com/CodelyTV/php-ddd-example/pull/188
