### ISSUE TITLE
¿Elasticsearch funcionando?

### ISSUE THREAD

**Issue by bareser** [CodelyTV/php-ddd-example#183]
Hola compañeros! 
me surgen duda si en el repositorio está elasticsearch funcionando, es decir, veo que en las diferentes clases de persistencia entra en juego llamadas a elasticsearch. Incluso si vamos al archivo .env veo que hay definidas variables de configuración para elasticsearch, aqui echo en falta el puerto por ejemplo.
Pero en el fichero docker-compose.yml no hay ninguna mención a elasticsearch.

¿Esto es correcto o me estoy saltando algo que no veo?

despues cuando estoy ejecutando el proyecto si accedo a localhost:9200 no funciona nada, incluso si pruebo desde el archivo backoffice_frontend.http las llamadas de prueba no funcionan, me dan error: "el servicio no esta running".

¿alguien me puede ayudar con esto?
mil gracias de antemano.

**Comment by bareser** [comment]
Gracias @rgomezcasas

**Comment by rgomezcasas** [comment]
Dooone! 😊
