### ISSUE TITLE
Doctrine YAML mapping is going to be deprecated in version 3

### ISSUE THREAD

**Issue by DanielRamosAcosta** [CodelyTV/php-ddd-example#199]
Greetings CodelyTV folks!

I'm not a PHP dev, but I've been investigating about Doctrine (to see if I can grab any implementation strategies to my node project) and I've found that the [YAML mapping is going to be deprecated in version 3](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/yaml-mapping.html).

I think this is where ports and adapters architecture shines. The framework has deprecated something but this should only impact the implementation details of your repositories (video migrating from YAML mapping? 🙏 ).

I would create a PR, but I'm not a PHP dev and I wouldn't know what would be the best implementation, so I leave this here for you experts 😉.

Regards!

**Comment by agus757** [comment]
What a great idea for a video, will be awesome to view that.
🎥 + 🧽 = 🤩

**Comment by rgomezcasas** [comment]
That would be an awesome video, yes. 😬

We already migrated [almost all of our yamls to xml](https://github.com/CodelyTV/php-ddd-example/search?q=orm.xml&unscoped_q=orm.xml), but there are 3 remaining:
1. https://github.com/CodelyTV/php-ddd-example/blob/master/src/Mooc/Videos/Infrastructure/Persistence/Doctrine/VideoTitle.orm.yml
2. https://github.com/CodelyTV/php-ddd-example/blob/master/src/Mooc/Videos/Infrastructure/Persistence/Doctrine/VideoType.orm.yml
3. https://github.com/CodelyTV/php-ddd-example/blob/master/src/Mooc/Videos/Infrastructure/Persistence/Doctrine/Video.orm.yml

Feel free to create a pull request (using the other xml's as an example) 😬

If you don't feel confident enough, don't worry. We'll do that ourselves instead. ✌️

Thanks for the advice!!!
