### ISSUE TITLE
PUT a  CoursesPutController error

### ISSUE THREAD

**Issue by trio1234** [CodelyTV/php-ddd-example#205]
Cuando levanto el servicio  con docker-compose up  y hago un put a  http://localhost:8030/courses/1c351e07-480b-49e4-8448-54877dd8ba69?name=El titulo&duration=4 years

Me da el siguiente error...
Calculo tendra que ver con AddJsonBodyToRequestListener

{
    "code": "type_error",
    "message": "Typed property CodelyTv\\Mooc\\Courses\\Application\\Create\\CreateCourseCommand::$name must be string, null used"
}

**Comment by rgomezcasas** [comment]
¡Buenas!
Eso es porque no le estás enviando los datos por el `body`, sino por `get parameters`.

[Aquí puedes ver un ejemplo](https://github.com/CodelyTV/php-ddd-example/blob/7fe73761611dfd66c3773af08c1d13644133a866/etc/endpoints/mooc_backend.http) de cómo se debería de hacer la request.

Saludos.
