### ISSUE TITLE
Issue running the project - No such file or directory

### ISSUE THREAD

**Issue by Pijuli** [CodelyTV/php-ddd-example#227]
Hi!

When trying to install the project I get this message on all of the apps:

Warning: file_put_contents(/app/apps/backoffice/backend/var/cache/test/CodelyTv_Apps_Backoffice_Backend_BackofficeBackendKernelTestDebugContainerDeprecations.log): Failed to open stream: No such file or directory

Am I missing something?
Ubuntu 20.04, currently running many projects with docker...

![image](https://user-images.githubusercontent.com/1220004/105492013-8ed49880-5cb7-11eb-9066-a14bc512ceba.png)

**Comment by trio1234** [comment]
Hi  try delete /app/apps/backoffice/backend/var/cache folder and try again

**Comment by Pijuli** [comment]
I cant see that folder

![image](https://user-images.githubusercontent.com/1220004/105641332-a6607c80-5e83-11eb-8c4a-1a6d1217aab7.png)

Also tried down-ing all the whole project and cloning it again. Same error

**Comment by trio1234** [comment]
I think this is  file permision problem because  symfony create automatic this folder!
Sry my english isnt very good!
Try this

**Comment by trio1234** [comment]
Enter to the docker container   whit this command 

docker exec -it codelytv-php_ddd_skeleton-mooc_backend-php bash
 and execute this command 
 
 chown www-data:www-data -R   /app
 
 this can fix this!

**Comment by Pijuli** [comment]
That did the trick!
Thank you very much!
