### ISSUE TITLE
Add CourseCreator services definition and tests

### ISSUE THREAD

**Issue by rgomezcasas** [CodelyTV/php-ddd-example#24]
This was missing from https://github.com/CodelyTV/cqrs-ddd-php-example/pull/15

We need:
 * Services definitions for that pr
 * Behaviour tests
 * Integration test for the repository
 * Some behat test for the new endpoint

**Comment by JavierCane** [comment]
Mr. @stale bot, we really appreciate your work. However, it would be nice to maintain this very specific issue open. Would it be posible?

Thx!

PS: We should add some kind of `Backlog` label in order to avoid automatically flagging these issues as `Stale` 😅
