### ISSUE TITLE
Errror make build new version symfony

### ISSUE THREAD

**Issue by mariomorenodev** [CodelyTV/php-ddd-example#321]
Hello,

I am trying to run the make build a pessar that tells me that everything went well when doing docker ps, I do not see the backoffice ports of any, I alternatively execute docker-compose up and I see some errors in the console.

<pre>CONTAINER ID   IMAGE                                                 COMMAND                  CREATED         STATUS                                  PORTS                                                                                                                                               NAMES
389fb5ea163f   php-ddd-example_backoffice_backend_php                &quot;docker-php-entrypoi…&quot;   7 seconds ago   Restarting (1) Less than a second ago                                                                                                                                                       codely-php_ddd_skeleton-backoffice_backend-php
3c3da8bb3cc5   php-ddd-example_backoffice_frontend_php               &quot;docker-php-entrypoi…&quot;   7 seconds ago   Restarting (1) 1 second ago                                                                                                                                                                 codely-php_ddd_skeleton-backoffice_frontend-php
6919b13df097   php-ddd-example_mooc_backend_php                      &quot;docker-php-entrypoi…&quot;   7 seconds ago   Restarting (1) Less than a second ago                                                                                                                                                       codely-php_ddd_skeleton-mooc_backend-php
928a54632036   docker.elastic.co/elasticsearch/elasticsearch:8.2.3   &quot;/bin/tini -- /usr/l…&quot;   7 seconds ago   Up 6 seconds                            0.0.0.0:9200-&gt;9200/tcp, :::9200-&gt;9200/tcp, 0.0.0.0:9300-&gt;9300/tcp, :::9300-&gt;9300/tcp                                                                codely-php_ddd_skeleton-backoffice-elastic
761710980a1d   mariadb:10.7.4                                        &quot;docker-entrypoint.s…&quot;   7 seconds ago   Up 6 seconds (health: starting)         0.0.0.0:3360-&gt;3306/tcp, :::3360-&gt;3306/tcp                                                                                                           codely-php_ddd_skeleton-mooc-mysql
1b4052f8b651   rabbitmq:3.10.5-management                            &quot;docker-entrypoint.s…&quot;   7 seconds ago   Up 6 seconds                            4369/tcp, 5671/tcp, 15671/tcp, 15691-15692/tcp, 25672/tcp, 0.0.0.0:5630-&gt;5672/tcp, :::5630-&gt;5672/tcp, 0.0.0.0:8090-&gt;15672/tcp, :::8090-&gt;15672/tcp   codely-php_ddd_skeleton-rabbitmq
8a430942230d   prom/prometheus:v2.36.1                               &quot;/bin/prometheus --c…&quot;   7 seconds ago   Up 6 seconds                            0.0.0.0:9999-&gt;9090/tcp, :::9999-&gt;9090/tcp                                                                                                           codely-php_ddd_skeleton-prometheus
</pre>

![Captura desde 2022-09-09 10-43-37](https://user-images.githubusercontent.com/54634496/189364700-4e5b750e-d65d-45f4-be5e-12d5cf54c886.png)

**Comment by rgomezcasas** [comment]
This is caused because Symfony changed its CLI and we can't pin the old version.

To fix this, you should modify [every instance where we use it](https://github.com/CodelyTV/php-ddd-example/search?q=symfony+serve) and remove the `--force-php-discovery` part. 🙂

**Comment by mariomorenodev** [comment]
Thank you very much it worked
