### ISSUE TITLE
Database transaction boundary 

### ISSUE THREAD

**Issue by gabrielanhaia** [CodelyTV/php-ddd-example#356]
Hey there.

This is not 100% a request for a feature, but it might be interesting for some people to know (as for me).

I would like to know where you guys would wrap the database insertion into a transaction.

Looking at the project, my best guess would be here: https://github.com/CodelyTV/php-ddd-example/blob/835bc68b1559a0810168e25d0579d96f4f299deb/src/Shared/Infrastructure/Persistence/Doctrine/DoctrineRepository.php#L20

But I am not 100% sure.

Thanks a lot in advance, and feel free to close this issue if it is the wrong channel

**Comment by rgomezcasas** [comment]
Wrapping the Use Case or doing a middleware before the command handler. [Something like this](https://github.com/CodelyTV/php-ddd-example/blob/255ccf29ed882de12927841ca9ab0e09c3c36756/src/Shared/Infrastructure/Symfony/Bundle/DependencyInjection/Compiler/TransactionalWrapper.php) 🙂

**Comment by gabrielanhaia** [comment]
Thanks a lot @rgomezcasas
