### ISSUE TITLE
Deptrac support

### ISSUE THREAD

**Issue by pincher2012** [CodelyTV/php-ddd-example#378]
Hexagonal architecture introduces rules for the dependence of certain application layers on others. The tool helps track violations of these rules. Have you considered using this tool?

**Comment by rgomezcasas** [comment]
We're using [phpat](https://github.com/carlosas/phpat) for that. [You can see an example here](https://github.com/CodelyTV/php-ddd-example/blob/main/tests/Shared/SharedArchitectureTest.php).

It's code instead of yaml. 🙌
