### ISSUE TITLE
Use Autowiring for Application/Infrastructure Services

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/php-ddd-example#50]
Modify the Dependency Injection Container definition to use the autowiring feature while instantiating Application Services and Infrastructure ones

**Comment by kniziol** [comment]
@JavierCane Where and how those services are autowired now?

**Comment by rgomezcasas** [comment]
@kniziol You can see an example here: https://github.com/CodelyTV/php-ddd-example/blob/master/apps/mooc/backend/config/services.yaml :)
