### ISSUE TITLE
Add tests summary in CircleCI

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/php-ddd-example#79]
We should [store the tests execution result](https://circleci.com/docs/2.0/configuration-reference/#store_test_results) in order to see the timing evolution in CircleCI.

I don't know why, but despite having [configured it in the `make test` command](https://github.com/CodelyTV/cqrs-ddd-php-example/blob/master/Makefile#L25-L27), and [in the CircleCI config](https://github.com/CodelyTV/cqrs-ddd-php-example/blob/master/.circleci/config.yml#L23-L26), it's [not storing the test results and showing them in CircleCI](https://circleci.com/gh/CodelyTV/cqrs-ddd-php-example/347).

The problem wouldn't be with something related to CircleCI because it doesn't generate the XML report even when running the tests locally with the `make test` command :/

**Comment by rgomezcasas** [comment]
Using GH Actions now
