### ISSUE TITLE
Publish the PHP Docker image to speedup environment setup

### ISSUE THREAD

**Issue by JavierCane** [CodelyTV/php-ddd-example#89]
Publish the PHP Docker image to DockerHub registry in order to speedup local environment setup and CircleCI builds times.

* CodelyTV organization already created
* Invitation to the Owners team on the CodelyTV organization sent to your personal email (user `rgomezcasas`)
* [Instructions on how to publish an image](https://docs.docker.com/docker-hub/repos/#pushing-a-docker-container-image-to-docker-hub)

**Comment by rgomezcasas** [comment]
We could the GitHub Registry for that. But for now it's building quite fast so I'm closing this :)
